"""add raw_notices

Revision ID: 3a7259975316
Revises: 40a0c3391e49
Create Date: 2026-04-01 16:19:18.969175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7259975316'
down_revision: Union[str, Sequence[str], None] = '40a0c3391e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_notices_external_id'), 'raw_notices', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_notices_external_id'), table_name='raw_notices')
    op.drop_table('raw_notices')
    # ### end Alembic commands ###
