"""init tables

Revision ID: 44d323119adc
Revises: ae3123c863f7
Create Date: 2026-04-04 19:00:24.725099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d323119adc'
down_revision: Union[str, Sequence[str], None] = 'ae3123c863f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_state',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('iteration_token', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_state')
    # ### end Alembic commands ###
