"""add ingestion control

Revision ID: 626098d6e49f
Revises: 44d323119adc
Create Date: 2026-04-13 16:37:15.925137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626098d6e49f'
down_revision: Union[str, Sequence[str], None] = '44d323119adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('cpv_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ingestion_state', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('ingestion_state', sa.Column('config_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'ingestion_state', ['config_id'])
    op.create_foreign_key(None, 'ingestion_state', 'ingestion_config', ['config_id'], ['id'])
    op.drop_column('ingestion_state', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_state', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ingestion_state', type_='foreignkey')
    op.drop_constraint(None, 'ingestion_state', type_='unique')
    op.drop_column('ingestion_state', 'config_id')
    op.drop_column('ingestion_state', 'id')
    op.drop_table('ingestion_control')
    op.drop_table('ingestion_config')
    # ### end Alembic commands ###
