"""add processed to raw_notices

Revision ID: 63c38ac39260
Revises: 3a7259975316
Create Date: 2026-04-02 08:24:40.377002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c38ac39260'
down_revision: Union[str, Sequence[str], None] = '3a7259975316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_notices', sa.Column('processed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_raw_notices_processed'), 'raw_notices', ['processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_notices_processed'), table_name='raw_notices')
    op.drop_column('raw_notices', 'processed')
    # ### end Alembic commands ###
